# Generated by Django 4.2.17 on 2024-12-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixconnectapp', '0003_photographyimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographyimages',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
