# Generated by Django 4.2.17 on 2025-01-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixconnectapp', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
